name: PlanetGenerator
version: ${project.version}
main: com.joewuthrich.planetgenerator.PlanetGenerator
api-version: 1.16
authors: [ joewuthrich ]
description: Generate a random planet.

commands:
  planetgenerator:
    usage: /pg [radius] [overlay] [underlay] [block,list,comma,seperated] [gradient (true/false)]
    aliases: pg